server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.itheima.pojo
  configuration:
    map-underscore-to-camel-case: true



